version: "2"
services:
  proxy:
    image: spesnova/nginx-example
    ports:
      - 80:8080
    volumes_from:
      - web
    depends_on:
      - web
  web:
    build: .
    command: [bundle, exec, puma, -C, config/puma.rb]
    volumes:
      - /app/tmp
      - /app/public
    depends_on:
      - db
    links:
      - db
    env_file: .env
    environment:
      - RACK_ENV=production
      - RAILS_ENV=production
      - DATABASE_URL=postgres://hello:world@db:5432/example
  db:
    image: postgres:9.5.1
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=world
